### PR TITLE
docs: fix: quote URLs; add security & behaviorial opts (fixes #936)

### LINKED ISSUE #936: docs: fix: quote URLs; add security & behaviorial opts
Installation convenience scripts include cURL commands with a `?` in the URL, which is a special character in some shells (e.g. ZSH).

```
$ curl -s https://packagecloud.io/install/repositories/opentofu/tofu/script.rpm.sh?any=true -o /tmp/tofu-repository-setup.sh
zsh: no matches found: https://packagecloud.io/install/repositories/opentofu/tofu/script.rpm.sh?any=true
```

I'm not sure if the `?any=true` option is actually desired, but in either case it seems like it'd be worth quoting this.

Also noticed that the current cURL command doesn't strictly require HTTPS may write an error message to the the file instead of aborting on a bad status code.

### PR DESCRIPTION
**Pull request by parrotmac**
Installation convenience scripts include cURL commands with a `?` in the URL, which is a special character in some shells (e.g. ZSH). This change also adds a few more options to make the fetch more strict, hopefully avoiding user confusion.

Breakdown of options:
- `--proto '=https'` Permit only HTTPS
- `--tlsv1.2` Require TLS version 1.2 or later
- `-f` Fail fast on any non-OK status code
- `-s` (Existing) Silent/Don't show progress
- `-S` Show error, if any!
- `-L` Follow redirects (e.g. usually some kind of permanent redirect)

Resolves #936 

## Target Release

~1.6.0~ Not sure this is relevant

### CODE REVIEW

**Comment by janosdebugs** [comment]
Hey @parrotmac thank you very much for your contribution, this looks good. Did you have a chance to run the included tests scripts? (They are not yet run automatically, see  #923 )

**Comment by parrotmac** [comment]
> Hey @parrotmac thank you very much for your contribution, this looks good. Did you have a chance to run the included tests scripts? (They are not yet run automatically, see #923 )

I had not! Testing this now, I'm running into an issue on both this branch and `main`, so it appears to be an issue with my setup.

<summary>Error Logs
<details>

```
$ ./test-install-instructions.sh                                                                                                                                main
[+] Running 11/11
 ✔ Container install-ubuntu-convenience-1      Removed                                                                                                                                         0.0s 
 ✔ Container install-fedora-manual-1           Removed                                                                                                                                         0.0s 
 ✔ Container install-rockylinux-manual-1       Removed                                                                                                                                         0.0s 
 ✔ Container install-fedora-convenience-1      Removed                                                                                                                                         0.0s 
 ✔ Container install-debian-manual-1           Removed                                                                                                                                         0.0s 
 ✔ Container install-debian-convenience-1      Removed                                                                                                                                         0.0s 
 ✔ Container install-opensuse-convenience-1    Removed                                                                                                                                         0.0s 
 ✔ Container install-rockylinux-convenience-1  Removed                                                                                                                                         0.0s 
 ✔ Container install-ubuntu-manual-1           Removed                                                                                                                                         0.0s 
 ✔ Container install-opensuse-manual-1         Removed                                                                                                                                         0.0s 
 ✔ Network install_default                     Removed                                                                                                                                         0.2s 
[+] Running 11/11
 ✔ Network install_default                     Created                                                                                                                                         0.2s 
 ✔ Container install-fedora-manual-1           Created                                                                                                                                         0.1s 
 ✔ Container install-debian-convenience-1      Created                                                                                                                                         0.1s 
 ✔ Container install-fedora-convenience-1      Created                                                                                                                                         0.1s 
 ✔ Container install-opensuse-convenience-1    Created                                                                                                                                         0.1s 
 ✔ Container install-rockylinux-manual-1       Created                                                                                                                                         0.1s 
 ✔ Container install-debian-manual-1           Created                                                                                                                                         0.1s 
 ✔ Container install-opensuse-manual-1         Created                                                                                                                                         0.1s 
 ✔ Container install-ubuntu-convenience-1      Created                                                                                                                                         0.1s 
 ✔ Container install-rockylinux-convenience-1  Created                                                                                                                                         0.1s 
 ✔ Container install-ubuntu-manual-1           Created                                                                                                                                         0.1s 
Attaching to install-debian-convenience-1, install-debian-manual-1, install-fedora-convenience-1, install-fedora-manual-1, install-opensuse-convenience-1, install-opensuse-manual-1, install-rockylinux-convenience-1, install-rockylinux-manual-1, install-ubuntu-convenience-1, install-ubuntu-manual-1
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/data/deb.sh": permission denied: unknown
```

</details>
</summary>

Will report back if I find out why this is failing in general :eyes:

**Comment by parrotmac** [comment]
> > Hey @parrotmac thank you very much for your contribution, this looks good. Did you have a chance to run the included tests scripts? (They are not yet run automatically, see #923 )
> 
> I had not! Testing this now, I'm running into an issue on both this branch and `main`, so it appears to be an issue with my setup.
> Error Logs
> 
> Will report back if I find out why this is failing in general 👀

The `deb.sh` and `rpm.sh` files `needed` to be `+x` for me. Alternatively, we could probably modify the docker-compose to call the interpreter (`bash`) with the script. Added the referenced files as `+x` in this PR but happy to change.

**Comment by janosdebugs** [comment]
@parrotmac you shouldn't need those. There's a [`test-install-instructions.sh`](https://github.com/opentofu/opentofu/blob/main/website/docs/intro/install/test-install-instructions.sh) file in that folder that will test all the install instructions on all platforms to make sure everything still works.

**Review by janosdebugs — APPROVED** [review]
All installation instructions passed testing and it also looks good to me. Thank you for your contribution (although the mode changes for rpm.sh and and deb.sh are not necessary).

**Comment by parrotmac** [comment]
> @parrotmac you shouldn't need those. There's a [`test-install-instructions.sh`](https://github.com/opentofu/opentofu/blob/main/website/docs/intro/install/test-install-instructions.sh) file in that folder that will test all the install instructions on all platforms to make sure everything still works. It needs Docker installed though.

Yep, this script is what I used [here](https://github.com/opentofu/opentofu/pull/935#issuecomment-1830282557), but was I was getting errors from the containers being unable to start. I'm curious if maybe this failure doesn't happen with different settings (maybe on Windows as the host OS??). From my reading of the compose file I would expect to require those shell scripts to be executable.

**Comment by janosdebugs** [comment]
Thanks again @parrotmac, we'll wait for one more review and then I'll merge.

**Review by Yantrio — APPROVED** [review]

**Comment by janosdebugs** [comment]
Merged, it will be deployed the next time we roll out the website. Thank you for your help @parrotmac !

**Pull request merged**
