### PR TITLE
Enhancement: Flag enabling warnings to be treated as errors

### LINKED ISSUE #757: Add a flag to treat warnings as errors
### OpenTofu Version

```shell
1.6.0-alpha2
```

### Use Cases

In a number of environments (like mine), deprecation warnings are to be fixed before commit.

### Attempted Solutions

Only those ones that involve adding complex `grep` regexes and shell scripting.

### Proposal

Add a flag like `-warnings-are-errors` or `-pedantic` to let the tool fail with non-zero return value also in case of warnings.
Default behavior would not treat warnings as error, thus retaining backward compatibility.

### References

_No response_

### PR DESCRIPTION
**Pull request by bunniseng**
Added a pedantic flag which enables warnings to be treated as errors.

Changes
- xx

Resolves #757

## Target Release

1.8.0

### CODE REVIEW

**Comment by cam72cam** [comment]
@bunniseng Sorry I did not comment sooner, but the approach you are taking is a much larger change than was anticipated.  Can we stop and talk about your approach?

**Comment by cam72cam** [comment]
Specifically, I think that this comment may indicate we could use a simpler approach:
https://github.com/opentofu/opentofu/issues/757#issuecomment-2134929046

**Comment by bunniseng** [comment]
No problem! I figured we would have this conversation after looking at the touch points of the change.

I looked over https://github.com/opentofu/opentofu/issues/757#issuecomment-2134929046 and that relates to the view layer components (main Ui / command view etc), is this ticket to be scoped to converting the view layer warnings to errors only when the pedantic option is enabled ?

Also with the tfdiags changes I've done, my thinking was that it would be better to go with the approach I have instead of switching the severity flags from exported package constants to mutable exported package variables, I generally shy away from introducing public globals if I can as it can lead to headaches down the road, but this is an option if we want to reduce the touch points?

Happy for some direction on this :) it did turn out to be a bit bigger than I had initially anticipated as well!

**Comment by bunniseng** [comment]
I'm going to look at another approach to reduce the amount of change, will update a comment for initial review in the next few days.

**Pull request closed without merging**
