### PR TITLE
Fix crash during destroy planning due to validation

### LINKED ISSUE #817: `tofu` crashes when destroying resources using variables with `validation` block
### OpenTofu Version

```shell
1.6.0-alpha3
```

### OpenTofu Configuration Files

**main.tf:**
```hcl
module "local" {
    source = "./local"

    resource_directory = "resource.secondary"
}

provider "tfcoremock" {
    alias = "secondary"

    resource_directory = module.local.resource_directory
}

resource "tfcoremock_simple_resource" "resource" {
    provider = tfcoremock.secondary
}
```
**local/main.tf:**
```hcl
variable "resource_directory" {
    type = string

    validation {
      condition = var.resource_directory == "resource.secondary"
      error_message = "hello"
    }
}

resource "tfcoremock_simple_resource" "simple" {
    string = var.resource_directory
}

output "resource_directory" {
    value = tfcoremock_simple_resource.simple.string
}
```

### Debug Output

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

OpenTofu crashed! This is always indicative of a bug within OpenTofu.
Please report the crash with OpenTofu[1] so that we can fix this.

When reporting bugs, please include your OpenTofu version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/opentofu/opentofu/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

checkable object status report for unexpected checkable object module.local.var.resource_directory
goroutine 1007 [running]:
runtime/debug.Stack()
	/Users/arelrabinowitz/sdk/go1.20.7/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/Users/arelrabinowitz/sdk/go1.20.7/src/runtime/debug/stack.go:16 +0x1c
github.com/opentofu/opentofu/internal/logging.PanicHandler()
	/Users/arelrabinowitz/Projects/opentf/internal/logging/panic.go:58 +0x16c
panic({0x1040aecc0, 0x140008fa240})
	/Users/arelrabinowitz/sdk/go1.20.7/src/runtime/panic.go:890 +0x230
github.com/opentofu/opentofu/internal/checks.(*State).reportCheckResult(0x14000b25b30, {0x104666d40, 0x1400106a840}, 0x6, 0x0, 0x50)
	/Users/arelrabinowitz/Projects/opentf/internal/checks/state_report.go:106 +0x55c
github.com/opentofu/opentofu/internal/checks.(*State).ReportCheckResult(0x14000b25b30, {0x104666d40, 0x1400106a840}, 0x6, 0x0, 0x50)
	/Users/arelrabinowitz/Projects/opentf/internal/checks/state_report.go:71 +0xac
github.com/opentofu/opentofu/internal/tofu.evalVariableValidations({{0x14000881da0, 0x1, 0x1}, {{}, {0x14000126ed0, 0x12}}}, 0x14000889040, {0x104661718, 0x1400053aae0}, {0x104670fb8, ...})
	/Users/arelrabinowitz/Projects/opentf/internal/tofu/eval_variable.go:252 +0xc2c
github.com/opentofu/opentofu/internal/tofu.(*nodeModuleVariable).Execute(0x140009b6cc0, {0x104670fb8, 0x14000554540}, 0x5)
	/Users/arelrabinowitz/Projects/opentf/internal/tofu/node_module_variable.go:198 +0x560
github.com/opentofu/opentofu/internal/tofu.(*ContextGraphWalker).Execute(0x1400073de60, {0x104670fb8, 0x14000554540}, {0x12df088d8, 0x140009b6cc0})
	/Users/arelrabinowitz/Projects/opentf/internal/tofu/graph_walk_context.go:143 +0xd8
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk.func1({0x1043cebe0, 0x140009b6cc0})
	/Users/arelrabinowitz/Projects/opentf/internal/tofu/graph.go:78 +0x3f0
github.com/opentofu/opentofu/internal/dag.(*Walker).walkVertex(0x140009b6d80, {0x1043cebe0, 0x140009b6cc0}, 0x1400137ee80)
	/Users/arelrabinowitz/Projects/opentf/internal/dag/walk.go:384 +0x324
created by github.com/opentofu/opentofu/internal/dag.(*Walker).Update
	/Users/arelrabinowitz/Projects/opentf/internal/dag/walk.go:307 +0xd7c
```

### Expected Behavior

Should destroy successfully and not crash

### Actual Behavior

Crashes

### Steps to Reproduce

1. `tofu init`
2. `tofu apply`
3. `tofu destroy`

### Additional Context

_No response_

### References

- Related issue in Terraform repository: https://github.com/hashicorp/terraform/issues/34052

### PR DESCRIPTION
**Pull request by cam72cam**
The original functionality of not validating during "apply" was added in c9bc7e8.  This unfortunately caused destroy to break as the validation checks were not pre-populated.

The change adopted by Terraform was to only run the validations if the action is not destroy: https://github.com/hashicorp/terraform/pull/34101

I decided to take a different approach and instead remove the special case around validating only during planning (and partially during apply. Additional calls into validation are cached during the plan -> apply cycle and don't incur a dramatic performance penalty.  I also believe the approach is simpler and easier to understand.

Resolves #817 

## Target Release

1.6.0

### BUG FIXES
* Addresses crash during tofu destroy inside module with variable validation.

### CODE REVIEW

**Review by cube2222 — APPROVED** [review]
LGTM

I agree this looks more "proper" a solution, with fewer possible surprising edge-cases (like the very referenced issue - a panic).

**Review by Yantrio — CHANGES_REQUESTED** [review]
I think overall this approach is great, I would like it if we could add some tests that went through the full flow.
ie:
- Have a variable with validation attached
- run a plan
- run through apply
- destroy the resources

and ensure that it works fully. This makes sure that we don't regress in the future

**Comment by cam72cam** [comment]
That sounds good @Yantrio.  I also want to play with the output_node and make sure there are not additional changes needed there.

**Review by cube2222 — COMMENTED** [review]
(the approach here also ties in well with [my recent proposal](https://github.com/opentofu/opentofu/issues/812), where we would actually want to run validation in the apply step, as in planning the inputs could be unknown)

**Comment by cam72cam** [comment]
@Yantrio this is ready for another pass as I have added the requested tests.  I've also confirmed that we do not need to make this change to output_node (which matches the similar Terraform changes).

**Review by Yantrio — APPROVED** [review]

**Review by cube2222 — APPROVED** [review]

**Pull request merged**
