### PR TITLE
Update .goreleaser.yaml

### PR DESCRIPTION
**Pull request by professorabhay**
Resolved the confliction as per #805

### CODE REVIEW

**Comment by professorabhay** [comment]
@mbialon, @Yantrio 👋

**Review by Yantrio — APPROVED** [review]

**Comment by Yantrio** [comment]
Hi @professorabhay , thanks for this PR.

Would you please sign off your commit for the DCO check please? You can find more information on that here: https://github.com/opentofu/opentofu/pull/853/checks?check_run_id=18567677143

**Comment by professorabhay** [comment]
Hey, @Yantrio ! Are there any other changes you are looking for ?

**Comment by Yantrio** [comment]
Hi @professorabhay , it looks like this PR has pulled in commits from another branch,  maybe there was an error in rebasing?

**Comment by professorabhay** [comment]
I think the provided commands for sign off by dco automatically signed PRs which are not signed. And, I think that it will not create any errors. Hopefully !

**Comment by professorabhay** [comment]
I think I created a mesh. So, I should close this PR and open a new one ?

**Comment by cam72cam** [comment]
You could rebase and drop thos earlier commits.  Let us know if you would like help with that

**Pull request closed without merging**
