### PR TITLE
Retag package docker image

### LINKED ISSUE #452: Change the release process to use `tofu`
Binary, docker images, git references needs to be changed to `opentofu`

### PR DESCRIPTION
**Pull request by alex067**
Retags the docker image built under the `package-docker` job in the build pipeline, as the image was previously being tagged under the `hashicorp` namespace.

part of #451 

## Target Release

1.6.0

### BUG FIXES 

 

- No user facing changes, as the packaged docker image is not available for external users.

### CODE REVIEW

**Comment by eranelbaz** [comment]
Hey, this one is a duplicate of https://github.com/opentofu/opentofu/pull/456 + https://github.com/opentofu/opentofu/pull/522
Please for the next pull request, make sure to check if no one didn't already start to work on it
thank you for understanding.

**Comment by alex067** [comment]
Hey @eranelbaz thanks for the feedback.

Checking those two prs, I don't believe they are a duplicate because they don't contain the fix of altering the hashicorp namespace as the docker tag.

**Comment by eranelbaz** [comment]
@alex067 please open a relevant issue for those namespaces and alter the linked issue 🙏 
Reopening

**Comment by eranelbaz** [comment]
I altered the description to say `part of #451`

**Review by eranelbaz — APPROVED** [review]

**Comment by eranelbaz** [comment]
Sorry for the misunderstanding and thank you for noticing!

**Pull request merged**
