### PR TITLE
add e2e test to cover the panic case of unknown conditional with sensitive

### PR DESCRIPTION
**Pull request by eranelbaz**
part of #655

## Target Release

1.6.0

### NEW FEATURES | UPGRADE NOTES | ENHANCEMENTS | BUG FIXES | EXPERIMENTS

 

-

### CODE REVIEW

**Comment by Yantrio** [comment]
Would you also be able to include a test for other types please? (collections, maps, numbers etc)

**Comment by Yantrio** [comment]
Also, whilst we're looking in this area, we should also cover destroy and apply test cases too. not just planning.

**Comment by cube2222** [comment]
Maybe we can keep have one test for each of the types and also one for apply? To not create too many of them (something would've need to be very messed up for it to work in apply but fail in destroy)

**Comment by eranelbaz** [comment]
Under the same `tf` file i'm adding the rest of the types
And I'll run it also for `apply`

**Comment by eranelbaz** [comment]
@Yantrio @cube2222 9337e8b7

**Review by Yantrio — APPROVED** [review]

**Comment by eranelbaz** [comment]
Renamed to folder - removed the `destroy` 
d0aa8172

**Review by cube2222 — APPROVED** [review]

**Pull request merged**
