### PR TITLE
ensure authorization header is included for http backends

### LINKED ISSUE #1656: Custom authorization header for http backend is dropped
### OpenTofu Version

```shell
OpenTofu v1.7.1
on darwin_arm64
```

### OpenTofu Configuration Files

```hcl
terraform {
  backend "http" {
    address = "http://localhost:8000"
    headers = {
        "authorization" = "Bearer access-token"
        "Cache-Control" = "no-cache"
    }
  }
}
```

### Debug Output

Initializing the backend...
2024-05-18T13:34:23.144-0500 [TRACE] Meta.Backend: built configuration for "http" backend with hash value 3930140512
2024-05-18T13:34:23.144-0500 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2024-05-18T13:34:23.144-0500 [DEBUG] New state was assigned lineage "8ef6b437-6995-5c21-7e6b-c8bed03ddc5c"
2024-05-18T13:34:23.144-0500 [TRACE] Meta.Backend: moving from default local state only to "http" backend
2024-05-18T13:34:23.144-0500 [DEBUG] checking for provisioner in "."
2024-05-18T13:34:23.145-0500 [DEBUG] checking for provisioner in "/opt/homebrew/bin"
2024-05-18T13:34:23.145-0500 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2024-05-18T13:34:23.145-0500 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2024-05-18T13:34:23.145-0500 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2024-05-18T13:34:23.145-0500 [TRACE] statemgr.Filesystem: read nil snapshot
2024-05-18T13:34:23.145-0500 [TRACE] Meta.Backend: ignoring local "default" workspace because its state is empty
2024-05-18T13:34:23.148-0500 [DEBUG] New state was assigned lineage "bb51cbaf-bd80-b95a-b781-5494d3af9f53"
2024-05-18T13:34:23.148-0500 [TRACE] Preserving existing state lineage "bb51cbaf-bd80-b95a-b781-5494d3af9f53"

Successfully configured the backend "http"! OpenTofu will automatically
use this backend unless the backend configuration changes.
2024-05-18T13:34:23.152-0500 [TRACE] Meta.Backend: instantiated backend of type *http.Backend
2024-05-18T13:34:23.152-0500 [DEBUG] checking for provisioner in "."
2024-05-18T13:34:23.152-0500 [DEBUG] checking for provisioner in "/opt/homebrew/bin"
2024-05-18T13:34:23.153-0500 [TRACE] Meta.Backend: backend *http.Backend does not support operations, so wrapping it in a local backend
2024-05-18T13:34:23.153-0500 [DEBUG] GET http://localhost:8000/
Error refreshing state: HTTP remote state endpoint invalid auth

### Expected Behavior

On my server I printed the headers attached to the HTTP request and got the following:

```
{'host': 'localhost:8000', 'user-agent': 'Go-http-client/1.1', 'cache-control': 'no-cache', 'accept-encoding': 'gzip'}
```

### Actual Behavior

I expect the authorization header to be contained in the list of headers. It looks like any other header works besides the `authorization` one

### Steps to Reproduce

1. Set up a simple http endpoint that prints headers for a request
2. `tofu init`

### Additional Context

I believe this is because of this line here: https://github.com/bunniseng/opentofu/blob/main/internal/backend/remote-state/http/backend.go#L261

which doesn't fall through to the default case

### References

_No response_

### PR DESCRIPTION
**Pull request by boetro**
Resolves #1656

## Target Release

1.8.0

## Checklist

- [ x ] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [ x ] I have not used an AI coding assistant to create this PR.
- [ x ] I have marked any code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from. 

### Go checklist

 

- [ x ] I have run golangci-lint on my change and receive no errors relevant to my code.
- [ x ] I have run existing tests to ensure my code doesn't break anything.
- [ x ] I have added tests for all relevant use cases of my code, and those tests are passing.
- [ x ] I have only exported functions, variables and structs that should be used from other packages.
- [ x ] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

**Review by cube2222 — APPROVED** [review]
Looks good, thanks for the fix!

Note to @opentofu/core-engineers, we should backport this for 1.7.2.

**Comment by cube2222** [comment]
@boetro looks like golangci-lint is complaining.

**Review by cam72cam — DISMISSED** [review]

**Comment by cam72cam** [comment]
The remaining lint issue is matching code in a lower case statement and can be ignored.

**Comment by cube2222** [comment]
@boetro No worries, but there's still one more linter issue.

To clarify, the reason why it doesn't complain about the `default:` part of the switch is because we only recently enabled golangci-lint and it only applies to new code. Feel free to fix both the lines it's complaining about and the line in the default (by e.g. panicking).

**Comment by boetro** [comment]
@cube2222 ok should be good this time

**Comment by cube2222** [comment]
Thanks for the contribution!

**Pull request merged**
