### PR TITLE
#300: Implement statically evaluated provider references

### LINKED ISSUE #300: Dynamic provider configuration assignment
Suggest an existing issue in legacy Terraform to fix in OpenTF. 

To increase automation we struggle many times when configuring providers. It would be great to finally be able to configure them dynamically or at least to be able to dynamically reference them instead of having all of that statically typed

---

Implementation PR: https://github.com/opentofu/opentofu/pull/2054

### PR DESCRIPTION
**Pull request by ollevche**
Resolves #300.

This PR encapsulates all the #300 implementation parts made by @cam72cam, @Evi1Pumpkin, and @ollevche.

Related info:
* https://github.com/opentofu/opentofu/issues/300
* [RFC on statically evaluated provider references](https://github.com/opentofu/opentofu/blob/main/rfc/20240513-static-evaluation-providers.md)
* [Provider references docs](https://github.com/opentofu/opentofu/blob/main/docs/provider-references.md)
* [Detailed breakdown of graph-related changes](https://github.com/opentofu/opentofu/pull/1963#issue-2502217685)

TODOs:

- [x] We have a little bug with this approach that if an existing resource in the state had a ResourceProvider and its configuration changed and now it uses InstanceProvider (or vice versa), we need to explicitly delete the old provider configuration. This is a known bug that I still need to handle and is quite easy to fix. [(c) Ronny](https://github.com/opentofu/opentofu/pull/1963#issue-2502217685)
- [x] Flows that were altered and need some love in testing: deposed flow, import flow, state show command (resource / resource index), taint command, untaint command, provider functions. [(c) Ronny](https://github.com/opentofu/opentofu/pull/1963#issue-2502217685)
- [ ] ~~Address recent discussion around the UX of removing provider configuration instances: https://github.com/opentofu/opentofu/issues/300#issuecomment-2387458333~~
- [x] Deal with deposed resource instances: https://github.com/opentofu/opentofu/pull/1963#discussion_r1773191916
- [ ] Decide what to do with https://github.com/opentofu/opentofu/pull/2088 (Draft PR: #2089)

Next Steps:
- [x] Merge #2069 into main
- [x] Merge #2065 into this feature branch
- [x] Merge #2074 into this feature branch
- [x] Rename a few fields
  - [x] states.ResourceInstance.InstanceProvider -> ProviderConfig
  - [x] "instance_provider" in state to "provider"
  - [x] states.EnsureResourceExists -> states.EnsureResource
  - [ ] NodeAbstractResourceInstance.ResolvedInstanceProvider -> ResolvedProvider
- [ ] Discuss returning Alias vs LocalProviderConfig from ProvidedBy
- [x] Rebase this branch on top of latest main - @cam72cam 
- [x] Fix linting
- [ ] Review inline comments and docstrings
- [ ] Documentation
- [ ] Changelog
- [ ] Merge into main
- [ ] Create teaser short - @abstractionfactory 
- [ ] Alpha release
- [ ] Blog Post - @abstractionfactory 

## Target Release

1.9.0

## Checklist

- [X] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [X] I have not used an AI coding assistant to create this PR.
- [X] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [X] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [ ] I have run golangci-lint on my change and receive no errors relevant to my code.
- [ ] I have run existing tests to ensure my code doesn't break anything.
- [ ] I have added tests for all relevant use cases of my code, and those tests are passing.
- [ ] I have only exported functions, variables and structs that should be used from other packages.
- [ ] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

**Comment by kubrickfr** [comment]
Being of the impatient type, I just gave this PR a spin.

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

OpenTofu crashed! This is always indicative of a bug within OpenTofu.
Please report the crash with OpenTofu[1] so that we can fix this.

When reporting bugs, please include your OpenTofu version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/opentofu/opentofu/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

ResolvedProvider for module.secondary_region["Milan"].module.vpc.aws_subnet.public[0] cannot get a provider
goroutine 4735 [running]:
runtime/debug.Stack()
	/usr/lib/go/src/runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
	/usr/lib/go/src/runtime/debug/stack.go:18 +0x13
github.com/opentofu/opentofu/internal/logging.panicHandler({0x2d25780, 0xc005db1380}, {0xc0066eb400, 0x39b, 0x400})
	/home/francois/BIG/Disposable/opentofu/internal/logging/panic.go:96 +0xd6
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk.PanicHandlerWithTraceFn.func2()
	/home/francois/BIG/Disposable/opentofu/internal/logging/panic.go:82 +0x8a
panic({0x2d25780?, 0xc005db1380?})
	/usr/lib/go/src/runtime/panic.go:785 +0x132
github.com/opentofu/opentofu/internal/tofu.(*NodeAbstractResourceInstance).ResolvedProvider(0xc002876508?)
	/home/francois/BIG/Disposable/opentofu/internal/tofu/node_resource_abstract_instance.go:99 +0x454
github.com/opentofu/opentofu/internal/tofu.(*NodePlannableResourceInstance).managedResourceExecute(0xc0065c5340, {0x39e4d08, 0xc00181fb00})
	/home/francois/BIG/Disposable/opentofu/internal/tofu/node_resource_plan_instance.go:167 +0xce
github.com/opentofu/opentofu/internal/tofu.(*NodePlannableResourceInstance).Execute(0x39b5580?, {0x39e4d08?, 0xc00181fb00?}, 0xb0?)
	/home/francois/BIG/Disposable/opentofu/internal/tofu/node_resource_plan_instance.go:92 +0x8a
github.com/opentofu/opentofu/internal/tofu.(*ContextGraphWalker).Execute(0xc0044eb200, {0x39e4d08, 0xc00181fb00}, {0x7d7b245c1528, 0xc0065c5340})
	/home/francois/BIG/Disposable/opentofu/internal/tofu/graph_walk_context.go:147 +0xb5
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk.func1({0x3316340, 0xc0065c5340})
	/home/francois/BIG/Disposable/opentofu/internal/tofu/graph.go:86 +0x3f8
github.com/opentofu/opentofu/internal/dag.(*Walker).walkVertex(0xc000b4b080, {0x3316340, 0xc0065c5340}, 0xc000b138c0)
	/home/francois/BIG/Disposable/opentofu/internal/dag/walk.go:385 +0x2d1
created by github.com/opentofu/opentofu/internal/dag.(*Walker).Update in goroutine 2947
	/home/francois/BIG/Disposable/opentofu/internal/dag/walk.go:308 +0xfb3
With go-routine called from:
goroutine 2947 [running]:
runtime/debug.Stack()
	/usr/lib/go/src/runtime/debug/stack.go:26 +0x5e
github.com/opentofu/opentofu/internal/logging.PanicHandlerWithTraceFn(...)
	/home/francois/BIG/Disposable/opentofu/internal/logging/panic.go:72
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk(0xc00693ce00, {0x39c4fc8, 0xc0044eb200})
	/home/francois/BIG/Disposable/opentofu/internal/tofu/graph.go:51 +0x3a
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk.func1({0x32ac540, 0xc003f21770})
	/home/francois/BIG/Disposable/opentofu/internal/tofu/graph.go:127 +0x833
github.com/opentofu/opentofu/internal/dag.(*Walker).walkVertex(0xc0028cf5c0, {0x32ac540, 0xc003f21770}, 0xc00127c840)
	/home/francois/BIG/Disposable/opentofu/internal/dag/walk.go:385 +0x2d1
created by github.com/opentofu/opentofu/internal/dag.(*Walker).Update in goroutine 81
	/home/francois/BIG/Disposable/opentofu/internal/dag/walk.go:308 +0xfb3

```

This is on a rather big tf codebase, but in essence this is what is done:

test.tfvars:
```terraform
environment        = "test"
master_region      = "eu-central-1"
master_vpc_cidr    = "10.1.0.0/16" 
secondary_regions  = {
  Ireland = { 
    region = "eu-west-1"
    vpc_cidr = "10.2.0.0/16" 
  }
  Milan = { 
    region = "eu-south-1"
    vpc_cidr = "10.3.0.0/16" 
  }
}
```
main.tf:
```terraform
# Provider configuration for master region
provider "aws" {
  alias = "aws_main"
  region = var.master_region
}

# Master region
module "master_region" {
  source = "./modules/master-region"

  providers = {
    aws = aws.aws_main
  }

  vpc_cidr                      = var.master_vpc_cidr
  environment                   = var.environment
  region                        = var.master_region
  secondary_regions             = var.secondary_regions
}

# Secondary regions

provider "aws" {
  for_each = var.secondary_regions
  region = each.value.region #var.secondary_regions.Ireland.region
}

module "secondary_region" {
  source   = "./modules/secondary-region"

  for_each = var.secondary_regions

  providers = {
    aws          = aws[each.key]
    aws.aws_main = aws.aws_main
  }

  region                                        = each.value.region
  main_aws_region                               = var.master_region
  vpc_cidr                                      = each.value.vpc_cidr
  main_vpc_id                                   = module.master_region.vpc_id
  main_route_table_id                           = module.master_region.main_route_table_id
}
```

secondary_region/modules/vpc/main.tf
```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      configuration_aliases = [aws.aws_main]
    }
  }
}

[...]

resource "aws_vpc_peering_connection" "master_to_secondary" {
  provider    = aws.aws_main
  vpc_id      = var.main_vpc_id
  peer_vpc_id = aws_vpc.secondary.id
  peer_region = var.secondary_region
}

```

The `secondary_region` has a lot of submodules, it uses the `aws.aws_main` provider in order to establish VPC peerings with the main region. It works well if I just created duplicate the `secondary_region` module and give it different names manually, which is what I have been doing until now and hoping this PR would improve.

**Comment by ollevche** [comment]
Thank you @kubrickfr for giving it a chance! I'll take a look at it tomorrow. I put the PR as draft because after all the merges I have to take another look at what needs to be glued properly and double-check existing todos in the code (it might be the reason of the crash).

**Comment by kubrickfr** [comment]
@ollevche Thanks! I did end-up removing all the weirdness with extra providers declared in submodules but to no avail, I always end up with the same crash in the submodules.

**Comment by kubrickfr** [comment]
@ollevche d3cbeb832713d1e03f9694a4e00d0db059cfd179 fixes the crash and deploys my configuration even with the extra providers for vpc peering between regions in sub sub modules.
A big thank you!

**Comment by kubrickfr** [comment]
Ok, after trying to apply a change, I'm getting:

```
Failed to marshal plan to json: no schema found for module.secondary_region["Ireland"].module.alb.aws_acm_certificate.control_plane (in provider %!s(PANIC=String method: called String on zero-value addrs.Provider))
```

**Comment by ollevche** [comment]
Hey @kubrickfr! We extremely appreciate your feedback on this feature. We are still finalizing the implementation design so not all the scenarios are working properly yet. But we are working on it!

**Comment by kubrickfr** [comment]
@ollevche I'm only trying to help finding possible edge cases. If this is counterproductive, just let me know and I'll wait for the bat-sginal! (but be assured there is no complaint/impatience on my side, only excitement)

**Comment by ollevche** [comment]
@kubrickfr no-no, we are happy to get early feedback, especially if you break things!

**Comment by cam72cam** [comment]
Scoped comparison of before/after force pushing:
```bash
# d36220e44cc65f54e246071911cd4436d64617c3 = origin/main at time of rebase
# 2a15e669477d74e7fc0de96d9be69c95c5f658e4 = rebased branch
# 130c0cb91c4b80e6b9e446d38af74010fce7e67c = original branch
git diff d36220e44cc65f54e246071911cd4436d64617c3 --numstat  | awk '{ print $3 }' | xargs git diff 2a15e669477d74e7fc0de96d9be69c95c5f658e4 130c0cb91c4b80e6b9e446d38af74010fce7e67c
```

**Comment by cam72cam** [comment]
@kubrickfr would you be up for trying the main feature branch now that things have stabilized a bit?

**Comment by kubrickfr** [comment]
@cam72cam I have been using it since this morning and have not had any issue. 
I'm looking forward to the released version so I can migrate our production environment 🚀

**Comment by ollevche** [comment]
In order to simplify the required changes, we decided to go with a different implementation path. See the updated RFC - https://github.com/opentofu/opentofu/pull/2115 and the new version of the implementation - https://github.com/opentofu/opentofu/pull/2105.

**Pull request closed without merging**
