### PR TITLE
Rename internal/cloud to OpenTofu

### LINKED ISSUE #487: Rename internal/cloud to OpenTofu

### PR DESCRIPTION
**Pull request by 7h3-3mp7y-m4n**
Rename internal/cloud to OpenTofu
[issues](uhttps://github.com/opentofu/opentofu/issues/451)

Resolves #487

### CODE REVIEW

**Review by eranelbaz — APPROVED** [review]
Thank you @7h3-3mp7y-m4n 
looking good

**Comment by 7h3-3mp7y-m4n** [comment]
snap .  1 task got failed .. I don't know why ?

**Comment by 7h3-3mp7y-m4n** [comment]
I saw that the file folder was having the typo for importing so maybe it might fix this

**Review by eranelbaz — APPROVED** [review]
Thank you!

**Pull request merged**
