### PR TITLE
Proper context propagation in Consul state backend implementation

### PR DESCRIPTION
**Pull request by marcinwyszynski**
While working on the context propagation in state backend implementations, I noticed that Consul was missing context handling entirely. I investigated the API a bit and figured out how to handle this properly. Here's my attempt on propagating the context to all Consul operations.

Related to #753

## Target Release

1.6.0

## Draft CHANGELOG entry

n/a since this is a pure housekeeping change

### CODE REVIEW

**Review by tomasmik — APPROVED** [review]

**Review by mbialon — APPROVED** [review]
Nit. What if we had one consistent way of creating options?

**Comment by marcinwyszynski** [comment]
@mbialon can you please elaborate? I think different calls require different option types, so my feeling is that we're as consistent as it gets?

**Comment by mbialon** [comment]
> @mbialon can you please elaborate? I think different calls require different option types, so my feeling is that we're as consistent as it gets?

One option is with the `var` expr like:

```
var queryOpts consulapi.QueryOptions
queryOpts.WithContext(ctx)

var writeOpts consulapi.WriteOptions
writeOpts.WithContext(ctx)
```

And the other is building the options in a single expr like:

```
writeOpts := (&consulapi.WriteOptions{}).WithContext(ctx)
```

**Comment by marcinwyszynski** [comment]
Oh I see @mbialon, thanks for the explanation. I'm actually going to do something slightly different and will make these options part of the struct. This way if someone wants to add support for more options for the backend they will have a nice central place to put it.

**Review by mbialon — APPROVED** [review]
Nice work!

**Review by tomasmik — APPROVED** [review]

**Comment by marcinwyszynski** [comment]
We are temporarily rolling back the context propagation on the backend. Once it's back in, we will merge it.

**Pull request closed without merging**
