### PR TITLE
Update textencodebase64 and textdecodebase64 documentation

### PR DESCRIPTION
**Pull request by asbiin**
Fix function name in description for `textencodebase64`, and add a signature function for `textdecodebase64`

## Target Release

1.8.0

### CODE REVIEW

**Comment by cam72cam** [comment]
@asbiin looks like the DCO signoff check is failing.  You will need to sign your commit as specified in the [contributing guidelines](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#writing-code-for-opentofu)

**Comment by asbiin** [comment]
> @asbiin looks like the DCO signoff check is failing. You will need to sign your commit as specified in the [contributing guidelines](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#writing-code-for-opentofu)

Thank you I've updated the branch with the signed off commit.

**Review by ollevche — APPROVED** [review]
Thank you for the fix!

**Comment by ollevche** [comment]
Sorry, I missed the destination branch of this PR so it became a backport for v1.7.

Here is the PR for the main branch: https://github.com/opentofu/opentofu/pull/1634

**Pull request merged**
