### PR TITLE
Update Release Process to use OpenTofu - part1

### PR DESCRIPTION
**Pull request by Hefeweizen**
This aligns a portion of the build process with the new project name.  It does not update the generated binary name.

relates to [#452](https://github.com/opentofu/opentofu/issues/452)

## Target Release

1.6.0

## Draft CHANGELOG entry

n/a as this is note code-related; it updates metadata about the project identity.

### NEW FEATURES | UPGRADE NOTES | ENHANCEMENTS | BUG FIXES | EXPERIMENTS

This aligns a portion of the build process with the new project name.
-  

I structured the PR as two commits.  The first updates the project name.  The second condenses the YAML, hopefully allowing easier future updates (one location to change, rather than multiple).

To validate the YAML is generally the same, `yq` will expand the anchors:
```bash
diff -yw --ignore-blank-lines <(g show @~1:.goreleaser.yaml | tr -d '"') <(yq -P 'explode(.)' .goreleaser.yaml  )
```

### CODE REVIEW

**Comment by Hefeweizen** [comment]
I'm baffled that Github is flagging a conflict.  The files tab correctly shows the paired commits successfully modifying main.

If anyone can explain this behaviour, I'd love to hear it.

**Comment by eranelbaz** [comment]
Hey @Hefeweizen 
Thank you for this PR, but it is a duplicate of https://github.com/opentofu/opentofu/pull/456 
Please, for next Issue you are trying to resolve, make sure to check if no one has already been assigned to it.

Currently closing it

**Comment by Hefeweizen** [comment]
@eranelbaz  Thanks for the update.  No problem on the closing.  I relied on the lack of links on the issue as a signal that no work had been done; that was insufficient.  But, as the project grows, ticket curation will get better.

**Comment by eranelbaz** [comment]
@Hefeweizen once pr is opened and linked you can see it on the side panel under development section

**Pull request closed without merging**
